#!/bin/bash
#
# SealGuard - Herramienta de Auditoria CRA
# Copyright (C) 2026 Alvaro Sanchez Garijo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Obligar al script a situarse en su propio directorio
cd "$(dirname "$0")" || exit 1

# Auto-escalada de privilegios (Sudo automático)
if [ "$EUID" -ne 0 ]; then
    # Ejecuta este mismo script con sudo, pasándole exactamente los mismos argumentos
    exec sudo "$0" "$@"
    # Si el usuario cancela el prompt de la contraseña, el script termina aquí
    exit 1
fi

# Gestión del entorno virtual
if [ ! -d "venv" ]; then
    echo -e "\e[36m[i]\e[0m Entorno virtual no detectado. Creándolo e instalando dependencias..."
    python3 -m venv venv
    
    if [ -f "requirements.txt" ]; then
        ./venv/bin/pip install -r requirements.txt
    else
        echo -e "\e[31m[ERROR]\e[0m ¡No se encuentra el archivo 'requirements.txt' en la carpeta actual!"
        exit 1
    fi
fi

# Comprobamos Nmap
if ! command -v nmap &> /dev/null; then
    echo -e "\e[33m[!]\e[0m 'nmap' no detectado. Procediendo a su instalación..."
    apt-get update -qq
    apt-get install -y nmap
    if [ $? -eq 0 ]; then
        echo -e "\e[32m[Ok]\e[0m Nmap instalado correctamente."
    else
        echo -e "\e[31m[ERROR]\e[0m Fallo al instalar Nmap. Abortando."
        exit 1
    fi
fi

# Comprobamos Osquery
if ! command -v osqueryi &> /dev/null; then
    echo -e "\e[33m[!]\e[0m 'osqueryi' no detectado. Añadiendo repositorio oficial e instalando..."
    
    # 1. Instalamos herramientas necesarias para añadir repos
    apt-get update -qq
    apt-get install -y curl gnupg software-properties-common
    
    # 2. Descargamos la clave GPG oficial de Osquery (método moderno y seguro para Ubuntu 24.04)
    curl -fsSL https://pkg.osquery.io/deb/pubkey.gpg | gpg --dearmor --yes -o /usr/share/keyrings/osquery-archive-keyring.gpg
    
    # 3. Añadimos el repositorio oficial a la lista de apt
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/osquery-archive-keyring.gpg] https://pkg.osquery.io/deb deb main" | tee /etc/apt/sources.list.d/osquery.list > /dev/null
    
    # 4. Actualizamos e instalamos
    apt-get update -qq
    apt-get install -y osquery
    
    if [ $? -eq 0 ]; then
        echo -e "\e[32m[Ok]\e[0m Osquery instalado correctamente."
    else
        echo -e "\e[31m[ERROR]\e[0m Fallo al instalar Osquery. Verifica tu conexión a internet."
        exit 1
    fi
fi

# Ejecutar la aplicación
./venv/bin/python main.py "$@"