# config/controls.yaml
# Configuración de Auditoría CRA - Perfil Servidor Linux General


project:
  nombre: "CRA Ubuntu Auditor"
  storage_path: "output"


#
network:
  white_list:
    - "ssh"
    - "http"
    - "https"
    - "ipp"         
    - "postgresql"
    - "mysql"
    - "domain"     

  black_list:
    "ftp": "Tráfico en texto plano. Usar SFTP."
    "telnet": "Acceso remoto inseguro. Usar SSH."
    "vnc": "Escritorio remoto no cifrado por defecto."
    "exec": "Comando remoto legacy."
    "login": "Login remoto legacy."
    "shell": "Shell remota legacy."
    "unknown": "Servicio desconocido o sospechoso (Posible Netcat/Listener crudo)."
    "bindshell": "Shell remota."
    "echo": "A menudo usado por Netcat."

# (Anexo I.1.2 - Gestión de vulnerabilidades)
vulnerabilities: 
  min_cvss_score: 7.0 # Reportar vulns de riesgo alto
  comp_kernel: true
  ignorar: [] # Paquetes de riesgo asumido
  timeout: 30 


#(Anexo I.1.2 - Gestión de identidades)
system: 
  
  updates:
    check_unattended_upgrades: true 
    check_days_since_last_update: 7


# (Anexo I.1.3 - Integridad de datos y sistema)
integrity: 
  monitored_binaries:
    - "/bin/ls"
    - "/bin/ps"
    - "/bin/netstat"
    - "/bin/login"
    - "/usr/bin/sudo"
    - "/usr/sbin/sshd"

  monitored_configs:
    - "/etc/hosts"
    - "/etc/resolv.conf"
    - "/etc/fstab"


# (Anexo I.1.4 - Confidencialidad)
# (Anexo I.1.4 - Confidencialidad y Bastionado)
hardening: 
  critical_files:
    - path: "/etc/shadow"
      max_permissions: "640" # rw-r-----
      owner: "root"
    - path: "/etc/passwd"
      max_permissions: "644" # rw-r--r--
      owner: "root"
    - path: "/etc/ssh/sshd_config"
      max_permissions: "600" # rw-------
      owner: "root"
    - path: "/etc/crontab"
      max_permissions: "644"
      owner: "root"
    - path: "/etc/sudoers" 
      max_permissions: "440"
      owner: "root"
  
  suid_sgid:
    critical_directories: ["/tmp/", "/home/", "/dev/shm/"]
    forviden_permissions: ["2", "3", "6", "7"] # w, wx, rw, rwx

  ssh:
    permit_root_login: ["no", "prohibit-password"]
    password_authentication: "no"
    protocol: "2"

  firewall_services:
    - "ufw.service"
    - "firewalld.service"
    - "iptables.service"
    - "nftables.service"

  system_checks:
    check_suid_sgid: true
    check_aslr: true
    check_mac: true # AppArmor / SELinux

  certificates:
    check_expiration_days: 30
    private_keys_path: "/etc/ssl/private/"
    max_key_permissions: "600"

  encryption: 
    algoritmo: "sha256"
    critical_mounts: ["/", "/home", "/var"]


# (Anexo I.1.5 - Resiliencia)
backups: 
  comp_crontab: true
  comp_systemd_timers: true
  keywords: ["backup", "rsync", "tar", "snapshot", "aws s3", "rclone"]



users:
    check_root_locked: false # En Ubuntu cloud a veces root está bloqueado (passwd -l)
    disallow_empty_passwords: true
    max_password_days: 90
    critical_groups: ["root", "sudo", "adm"]
    politics: ["PASS_MAX_DAYS", "PASS_MIN_DAYS", "PASS_WARN_AGE", "UID_MIN", "USERGROUPS_ENAB", "DEFAULT_HOME", "LOGIN_RETRIES", "LOGIN_TIMEOUT"]
    mfa:
      modulos_pam_2fa: 
        - "pam_google_authenticator.so"
        - "pam_duo.so"
        - "pam_yubico.so"
        - "pam_u2f.so"

      servicios_pam_a_revisar:
        - "sshd"
        - "sudo"
        - "login"

      tokens_requeridos:
        ".google_authenticator": "pam_google_authenticator.so"
        ".yubico": "pam_yubico.so"