# config/controls.yaml
# Configuración de Auditoría CRA - Perfil Servidor Linux General


project:
  nombre: "CRA Ubuntu Auditor"
  storage_path: "output"


#
network:
  white_list:
    - "ssh"
    - "http"
    - "https"
    - "ipp"         
    - "postgresql"
    - "mysql"
    - "domain"     

  black_list:
    "ftp": "Tráfico en texto plano. Usar SFTP."
    "telnet": "Acceso remoto inseguro. Usar SSH."
    "vnc": "Escritorio remoto no cifrado por defecto."
    "exec": "Comando remoto legacy."
    "login": "Login remoto legacy."
    "shell": "Shell remota legacy."
    "unknown": "Servicio desconocido o sospechoso (Posible Netcat/Listener crudo)."
    "bindshell": "Shell remota."
    "echo": "A menudo usado por Netcat."

# (Anexo I.1.2 - Gestión de vulnerabilidades)
vulnerabilities: 
  min_cvss_score: 7.0 # Reportar vulns de riesgo alto
  comp_kernel: true
  ignorar: [] # Paquetes de riesgo asumido
  timeout: 30 


#(Anexo I.1.2 - Gestión de identidades)
system: 
  
  updates:
    check_unattended_upgrades: true 
    check_days_since_last_update: 7


# (Anexo I.1.3 - Integridad de datos y sistema)
integrity: 
  monitored_binaries:
    - "/bin/ls"
    - "/bin/ps"
    - "/bin/netstat"
    - "/bin/login"
    - "/usr/bin/sudo"
    - "/usr/sbin/sshd"

  monitored_configs:
    - "/etc/hosts"
    - "/etc/resolv.conf"
    - "/etc/fstab"



hardening: 
  critical_files:
    - path: "/etc/shadow"
      max_permissions: "640" 
      owner: "root"
    - path: "/etc/passwd"
      max_permissions: "644" 
      owner: "root"
    - path: "/etc/ssh/sshd_config"
      max_permissions: "600" 
      owner: "root"
    - path: "/etc/crontab"
      max_permissions: "644"
      owner: "root"
    - path: "/etc/sudoers" 
      max_permissions: "440"
      owner: "root"

  
  suid_sgid:
    critical_directories: ["/tmp/", "/home/", "/dev/shm/"]
    forviden_permissions: ["2", "3", "6", "7"] # w, wx, rw, rwx

  ssh:
    secure_params:
      PermitRootLogin: "no"
      PermitEmptyPasswords: "no"
      PasswordAuthentication: "no"  # Obligamos a usar claves 
      MaxAuthTries: "4"             # Corta la conexión rápido si fallan
      MaxSessions: "2"

    allowed_users:
      - "usu_prueba@10.0.2.8"

  firewall_services:
    - "ufw.service"
    - "firewalld.service"
    - "iptables.service"
    - "nftables.service"

  system_checks:
    check_suid_sgid: true
    check_aslr: true
    check_mac: true # AppArmor / SELinux

  certificados:
    dias_aviso_caducidad: 30
    min_rsa_key_size: 2048
    algoritmos_permitidos: 
      - "sha256WithRSAEncryption"
      - "sha384WithRSAEncryption"
      - "sha512WithRSAEncryption"
      - "ecdsa-with-SHA256"
      - "ecdsa-with-SHA384"
    rutas_criticas:
    # Estas rutas son de ejemplo, generamos un certificado válido y otro peligrosos (para usar la herramienta sustituyalo con la estructura indicada)
#     - path: "/tmp/cert_malo.pem"
#       tipo: "publico"
#       max_permissions: "644"
#       owner: "root"
#     - path: "/tmp/clave_mala.pem"
#       tipo: "privado"
#       max_permissions: "600"
#       owner: "root"

  encryption: 
    algoritmo: "sha256"
    critical_mounts: ["/", "/home", "/var"]


disponibilidad: ["backup", "rsync", "aws s3", "rclone"]


users:
  check_root_locked: false # En Ubuntu cloud a veces root está bloqueado (passwd -l)
  disallow_empty_passwords: true
  max_password_days: 90
  critical_groups: ["root", "sudo", "adm"]
  politics: ["PASS_MAX_DAYS", "PASS_MIN_DAYS", "PASS_WARN_AGE", "UID_MIN", "USERGROUPS_ENAB", "DEFAULT_HOME", "LOGIN_RETRIES", "LOGIN_TIMEOUT"]
  mfa:
    modulos_pam_2fa: 
      - "pam_google_authenticator.so"
      - "pam_duo.so"
      - "pam_yubico.so"
      - "pam_u2f.so"

    servicios_pam_a_revisar:
      - "sshd"
      - "sudo"
      - "login"

    tokens_requeridos:
      ".google_authenticator": "pam_google_authenticator.so"
      ".yubico": "pam_yubico.so"

boot:
  param_kernel:
    white_list:
      - ["apparmor=1", "selinux=1", "enforcing=1"]  # Fuerza control de acceso obligatorio
      - "audit=1"
      - "slab_nomerage=1"
      - "page_poison=1"
    
    black_list:
      - ["init=/bin/bash", "init=single", "single"]
      - "nokaslr"
      - ["mitigations=off", "nopti"]

  contra_fisica: false

  integridad_kernel:
    white_list:
      - ["P", 1, "Módulo propietario cargado"]
      - ["I", 2048, "Workaround para bug de firmware aplicado"]
      - ["O", 4096, "Módulo externo (out-of-tree) cargado"]
      - ["T", 131072, "Kernel construido con struct randomization"]
      - ["N", 262144, "Test in-kernel ejecutado"]

    warning_list:
      - ["S", 4, "Kernel en un sistema fuera de especificación"]
      - ["U", 64, "Contaminación solicitada por aplicación de usuario"]
      - ["W", 512, "El kernel emitió un warning"]
      - ["C", 1024, "Se cargó un driver en fase de pruebas (staging)"]
      - ["K", 32768, "Kernel parcheado en vivo (live patched)"]
      - ["X", 65536, "Contaminación auxiliar definida por la distro"]

    black_list:
      - ["F", 2, "Módulo forzado a cargar"]
      - ["R", 8, "Módulo forzado a descargar"]
      - ["M", 16, "Excepción de chequeo de máquina (MCE) reportada por procesador"]
      - ["B", 32, "Página de memoria errónea referenciada"]
      - ["D", 128, "El kernel murió recientemente (OOPS o BUG)"]
      - ["A", 256, "Tabla ACPI sobrescrita por el usuario"]
      - ["E", 8192, "Módulo no firmado cargado"]
      - ["L", 16384, "Ocurrió un soft lockup"]
      - ["J", 524288, "Operación de depuración mutante usada por usuario"]
    


